###################
### MY PROGRAMS ###
###################

# Define frequently used programs
$terminal = alacritty
$menu = fuzzel
$browser = google-chrome-stable

#################
### AUTOSTART ###
#################

# Autostart essential applications
exec-once = hyprctl dispatch focusmonitor DP-3
exec-once = uwsm-app -- swaybg -i ~/Pictures/Wallpaper/wallpaper.png
exec-once = uwsm-app -- waybar
