general {
    grab_focus = true
}

finders {
    default_finder = desktop
    desktop_icons = true
    desktop_launch_prefix = uwsm app -- 
}

ui {
    window_size = 400 260
}

cache {
    enabled = true
}

